# Tutorials i TensorFlow fra Kieth Downing

In [1]:
from downing_code import tflowtools as TFT
from downing_code import tutor1, tutor2, tutor3

### Tutorial example 1:
Lager en multiplikasjon mellom 2 konstanter. Konstanter trenger ikke å initialiseres. Session kan dermed bli kjørt enkelt. Multiplikasjonen blir ikke egentlig utført før kallet til session.run(z).

In [3]:
tutor1.tfex1(5, 2)

10

### Tutorial example 2:
Dettte eksempelet gjør det samme som tfex1 over, men med variabler istedenfor konstaner. 

Variabler må initialisers før kallet til session.run(). Variablene får sin verdi tildelt ved kallet til initialize. Det går ikke å gjøre session uten initialiseringen. 

In [4]:
tutor1.tfex2(5, 2)

10

### Tutorial example 3A
Eksempelet lager 2 matriser, matrise Y og matrise Y.

X er en 2 dimensjonal matrise på 3x5. Den er fylt med tilfeldige verdier mellom 0 og 1.

Y er også en 2D matrise men på 5x1. Denne er fylt med tilfeldige verdier mellom 10 og 20.

NumPY order uniforme verdier i de forskjellige cellene.

tensorflow.matmul(x, y) utfører matrisemultiplikasjon (matmul = matrix multiplication).

Verdiene i de to matrisene blir ikke lagt inn før initialiserings kallet gjøres. Det samme gjelder tf.matmul(x,y). Denne er kun operasjonen. 

In [5]:
tutor1.tfex3()



[ 31.9515419]

[ 36.18543984]

[ 45.86372549]



### Tutorial example 3B
Eksempelet betsår av 3 matriser , W(3x5), X(5x1) og Y(3x1). Det er også 2 operatorer, z1, en matrisemultiplikasjon og z2, en addisjon mellom matriser. 

Igjen så skjer det ingenting før variablene initialiseres. 

Her blir det også sendt med 3 operatorer inn i quickrun, som en liste. Dette gjør at det blir skrevet ut alle tre operatorene. hver av disse kjøres også gjennom session.run().

In [6]:
tutor1.tfex3b()



[[ 0.00589087  0.35233849  0.80138443  0.90234664  0.3594748 ]
 [ 0.72015095  0.01600925  0.8308303   0.37128482  0.76654004]
 [ 0.88500683  0.31003289  0.71498322  0.63914779  0.63473571]]

[[ 39.65275148]
 [ 45.29110877]
 [ 52.1993477 ]]

[[ 145.53160447]
 [ 147.52591273]
 [ 155.96423725]]



### Tutorial example 4
Dette eksempelet dreier se gom å sette verdier til variabler. Her skjer det et par interessante ting. 

1. X2 settes til X1 sin verdi når X1 har blitt tildelt en verdi i realtime. tf.Variable().initialized_value() returnerer verdien en gitt variabel har på et gitt punkt i tid. Siden variabler alltid endrer verdier ettersom tensorflow kjører er dette en viktig funksjon. Det er slik man gir en variabel verdien til en annen variabel.
2. Assign setter en ny verdi til denne variabelen. Dette betyr at verdien X2 hadde når x.initialized_value() ble kalt blir overskrevet med en gang. Assignen inneholder også en matrise addisjon.

In [7]:
tutor1.tfex4()



[[ 1.53951777]
 [ 1.1416361 ]
 [ 1.08682182]
 [ 1.59693465]
 [ 1.52754636]]

[[ 119.79736332]
 [ 172.51124558]
 [ 198.13301835]
 [ 102.2765412 ]
 [ 110.10448866]]



# Tutorial example 5A & 5B
Begge disse eksemplene går ut på å vise tensorboard. Operasjoenene utenom er sett over. 

In [8]:
tutor1.tfex5()


The Grabbed Variables:
   w_1:0 = 
[[ 0.76271803  0.48860902  0.20096841  0.34768618  0.54723202]
 [ 0.20779416  0.28589641  0.10170639  0.93201282  0.603252  ]
 [ 0.24861456  0.1689891   0.91551501  0.87749793  0.17439887]]

   x_4:0 = 
[[ 17.86522675]
 [ 14.16850353]
 [ 15.62922618]
 [ 12.54009733]
 [ 18.67436464]]

   y_3:0 = 
[[ 105.1854695 ]
 [ 104.30994772]
 [ 108.83567732]]



[[array([[ 143.45466827],
         [ 136.61543339],
         [ 144.24104419]])],
 [array([[ 0.76271803,  0.48860902,  0.20096841,  0.34768618,  0.54723202],
         [ 0.20779416,  0.28589641,  0.10170639,  0.93201282,  0.603252  ],
         [ 0.24861456,  0.1689891 ,  0.91551501,  0.87749793,  0.17439887]]),
  array([[ 17.86522675],
         [ 14.16850353],
         [ 15.62922618],
         [ 12.54009733],
         [ 18.67436464]]),
  array([[ 105.1854695 ],
         [ 104.30994772],
         [ 108.83567732]])]]

In [9]:
tutor1.tfex5b()


The Grabbed Variables:
   w_2:0 = 
[[ 0.3101715   0.33703634  0.13702168  0.53572712  0.60111179]
 [ 0.10720767  0.26827591  0.68142487  0.03461809  0.6211281 ]
 [ 0.31441514  0.48707083  0.98680623  0.22287919  0.04733943]]

   x_5:0 = 
[[ 13.31846091]
 [ 10.00896066]
 [ 12.16447714]
 [ 10.00242071]
 [ 11.12579479]]

   y_4:0 = 
[[ 105.87772002]
 [ 104.8774355 ]
 [ 104.06418048]]



[[array([[ 127.0953219 ],
         [ 124.53642537],
         [ 127.8867811 ]])],
 [array([[ 0.3101715 ,  0.33703634,  0.13702168,  0.53572712,  0.60111179],
         [ 0.10720767,  0.26827591,  0.68142487,  0.03461809,  0.6211281 ],
         [ 0.31441514,  0.48707083,  0.98680623,  0.22287919,  0.04733943]]),
  array([[ 13.31846091],
         [ 10.00896066],
         [ 12.16447714],
         [ 10.00242071],
         [ 11.12579479]]),
  array([[ 105.87772002],
         [ 104.8774355 ],
         [ 104.06418048]])]]

# Tutorial example 6
Her introduseres feeder dict. En feeder dict mater inn verdier inn i en placeholder. Hver placeholder som er nevnt i feeder_dicten blir matet med alle sine verdier når dette kjøres.

In [10]:
tutor1.tfex6()


The Grabbed Variables:
   w_3:0 = 
[[ 0.11646402  0.41471294  0.50016077  0.66767794  0.60864888]
 [ 0.83845473  0.69484337  0.52754857  0.47951485  0.711566  ]
 [ 0.00877206  0.86334048  0.54663332  0.99742505  0.01522085]]

   x_6:0 = 
[[ 19.80315805]
 [ 11.78785937]
 [ 12.23336879]
 [ 11.89758964]
 [ 15.75349441]]

   y_5:0 = 
[[ 109.21999838]
 [ 104.5400199 ]
 [ 106.19971684]]



[[array([[ 140.06568762],
         [ 152.70320544],
         [ 135.34427008]])],
 [array([[ 0.11646402,  0.41471294,  0.50016077,  0.66767794,  0.60864888],
         [ 0.83845473,  0.69484337,  0.52754857,  0.47951485,  0.711566  ],
         [ 0.00877206,  0.86334048,  0.54663332,  0.99742505,  0.01522085]]),
  array([[ 19.80315805],
         [ 11.78785937],
         [ 12.23336879],
         [ 11.89758964],
         [ 15.75349441]]),
  array([[ 109.21999838],
         [ 104.5400199 ],
         [ 106.19971684]])]]

# Tutorial example 7
Her er feed dict i bruk sammen med en løkke. Operasjonen som utføres hver gang run blir kalt er "update x". Denne gir x verdien til en matrisemultiplikasjon + y. Dette gjøres for alle verdier i feed_dict for hver kjøring. 

En annen ting å merke seg her er at dette er interasksjonen mellom et input (x) variabel, et hidden layer (w=weights) og en output variabel (y).

Utføringen av dette ser slik ut: 

![Modell](../Modell.png)



In [2]:
tutor1.tfex7()


The Grabbed Variables:
   w:0 = 
[[-0.26144401  0.89451779  0.35937793  0.02727934 -0.44368184]
 [ 0.77072806 -0.10670939 -0.79251774  0.92554175 -0.67642648]
 [ 0.30342753 -0.92083488  0.52433145  0.91759257  0.34860253]
 [-0.6384351  -0.77870257 -0.01905593  0.42464578  0.51387439]
 [ 0.42224634 -0.30043967  0.14030107  0.15590419 -0.8134573 ]]

   x:0 = 
[[ 0.32225008  0.61438033 -0.93094689 -0.22903236  0.83344275]]

   y:0 = 
[[ 0.32225008  0.61438033 -0.93094689 -0.22903236  0.83344275]]


The Grabbed Variables:
   x:0 = 
[[ 0.92718541  1.62227579 -1.66887204 -0.4731573  -0.84531127]]


The Grabbed Variables:
   x:0 = 
[[ 0.76894539  3.42982154 -2.86804299 -0.56631178 -0.81257471]]


The Grabbed Variables:
   x:0 = 
[[ 1.91287702  4.26233363 -4.97981795 -0.03247365 -2.45757181]]


The Grabbed Variables:
   x:0 = 
[[ 0.5792577   7.21988126 -6.57673243 -1.19826211 -2.65195618]]


The Grabbed Variables:
   x:0 = 
[[  3.38504378   8.14803475 -10.24228438  -0.48797789  -5.05845092]]
